// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO7DKAmlwaS4bx1dUWI5C2jeThD4XR33s',
    appId: '1:24992553222:android:c139822ac9f7976cc4e687',
    messagingSenderId: '24992553222',
    projectId: 'restroom-near-u',
    storageBucket: 'restroom-near-u.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8hfw6u1xc5Ngmd8WxSqi7WSwWMfGNRfs',
    appId: '1:24992553222:ios:8b82755fb0c43a18c4e687',
    messagingSenderId: '24992553222',
    projectId: 'restroom-near-u',
    storageBucket: 'restroom-near-u.firebasestorage.app',
    androidClientId: '24992553222-8h5upt5anh9ka030sa17lhmivnmlb0mb.apps.googleusercontent.com',
    iosClientId: '24992553222-54oe8i1476a6l3rnf16i2evt826ec04p.apps.googleusercontent.com',
    iosBundleId: 'com.example.restroomNearu',
  );

}